/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameRouteImport } from './routes/game'
import { Route as TestModalsRouteImport } from './routes/test-modals'
import { Route as TestUiRouteImport } from './routes/test-ui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const TestModalsRoute = TestModalsRouteImport.update({
  id: '/test-modals',
  path: '/test-modals',
  getParentRoute: () => rootRouteImport,
} as any)
const TestUiRoute = TestUiRouteImport.update({
  id: '/test-ui',
  path: '/test-ui',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/test-modals': typeof TestModalsRoute
  '/test-ui': typeof TestUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/test-modals': typeof TestModalsRoute
  '/test-ui': typeof TestUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/test-modals': typeof TestModalsRoute
  '/test-ui': typeof TestUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game' | '/test-modals' | '/test-ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/test-modals' | '/test-ui'
  id: '__root__' | '/' | '/game' | '/test-modals' | '/test-ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  TestModalsRoute: typeof TestModalsRoute
  TestUiRoute: typeof TestUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-modals': {
      id: '/test-modals'
      path: '/test-modals'
      fullPath: '/test-modals'
      preLoaderRoute: typeof TestModalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-ui': {
      id: '/test-ui'
      path: '/test-ui'
      fullPath: '/test-ui'
      preLoaderRoute: typeof TestUiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  TestModalsRoute: TestModalsRoute,
  TestUiRoute: TestUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
