/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RichlistRouteImport } from './routes/richlist'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PlanetsRouteImport } from './routes/planets'
import { Route as Market_logsRouteImport } from './routes/market_logs'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as QuestsMissionRouteImport } from './routes/quests.$mission'
import { Route as MarketRelicsRouteImport } from './routes/market.relics'
import { Route as MarketCratesRouteImport } from './routes/market.crates'
import { Route as MarketConsumablesRouteImport } from './routes/market.consumables'
import { Route as UserSalvage_logsRouteImport } from './routes/$user.salvage_logs'
import { Route as UserRelicsRouteImport } from './routes/$user.relics'
import { Route as UserQuest_logsRouteImport } from './routes/$user.quest_logs'
import { Route as UserMarket_logsRouteImport } from './routes/$user.market_logs'
import { Route as UserItemsRouteImport } from './routes/$user.items'
import { Route as UserItem_logsRouteImport } from './routes/$user.item_logs'
import { Route as UserForge_logsRouteImport } from './routes/$user.forge_logs'
import { Route as UserCratesRouteImport } from './routes/$user.crates'
import { Route as UserConsumablesRouteImport } from './routes/$user.consumables'
import { Route as UserClaim_logsRouteImport } from './routes/$user.claim_logs'
import { Route as UserBoss_logsRouteImport } from './routes/$user.boss_logs'
import { Route as UserBattle_logsRouteImport } from './routes/$user.battle_logs'
import { Route as ApiMockStatsRouteImport } from './routes/api/mock/stats'
import { Route as ApiMockRichlistRouteImport } from './routes/api/mock/richlist'
import { Route as ApiMockQuest_boardRouteImport } from './routes/api/mock/quest_board'
import { Route as ApiMockMarketplace_logsRouteImport } from './routes/api/mock/marketplace_logs'
import { Route as ApiMockLeaderboardRouteImport } from './routes/api/mock/leaderboard'
import { Route as ApiMockItems_archiveRouteImport } from './routes/api/mock/items_archive'
import { Route as ApiMockBattleRouteImport } from './routes/api/mock/battle'
import { Route as ApiMockSalvage_logsUserRouteImport } from './routes/api/mock/salvage_logs.$user'
import { Route as ApiMockQuestsUserRouteImport } from './routes/api/mock/quests.$user'
import { Route as ApiMockPlayerUserRouteImport } from './routes/api/mock/player.$user'
import { Route as ApiMockNft_logsUserRouteImport } from './routes/api/mock/nft_logs.$user'
import { Route as ApiMockMarketplace_logsUserRouteImport } from './routes/api/mock/marketplace_logs.$user'
import { Route as ApiMockItemsUserRouteImport } from './routes/api/mock/items.$user'
import { Route as ApiMockForge_logsUserRouteImport } from './routes/api/mock/forge_logs.$user'
import { Route as ApiMockClaim_logsUserRouteImport } from './routes/api/mock/claim_logs.$user'
import { Route as ApiMockMarketplaceListingsRelicsRouteImport } from './routes/api/mock/marketplace.listings.relics'
import { Route as ApiMockMarketplaceListingsItemsRouteImport } from './routes/api/mock/marketplace.listings.items'
import { Route as ApiMockMarketplaceListingsConsumablesRouteImport } from './routes/api/mock/marketplace.listings.consumables'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RichlistRoute = RichlistRouteImport.update({
  id: '/richlist',
  path: '/richlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsRoute = PlanetsRouteImport.update({
  id: '/planets',
  path: '/planets',
  getParentRoute: () => rootRouteImport,
} as any)
const Market_logsRoute = Market_logsRouteImport.update({
  id: '/market_logs',
  path: '/market_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const QuestsMissionRoute = QuestsMissionRouteImport.update({
  id: '/quests/$mission',
  path: '/quests/$mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRelicsRoute = MarketRelicsRouteImport.update({
  id: '/relics',
  path: '/relics',
  getParentRoute: () => MarketRoute,
} as any)
const MarketCratesRoute = MarketCratesRouteImport.update({
  id: '/crates',
  path: '/crates',
  getParentRoute: () => MarketRoute,
} as any)
const MarketConsumablesRoute = MarketConsumablesRouteImport.update({
  id: '/consumables',
  path: '/consumables',
  getParentRoute: () => MarketRoute,
} as any)
const UserSalvage_logsRoute = UserSalvage_logsRouteImport.update({
  id: '/$user/salvage_logs',
  path: '/$user/salvage_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRelicsRoute = UserRelicsRouteImport.update({
  id: '/$user/relics',
  path: '/$user/relics',
  getParentRoute: () => rootRouteImport,
} as any)
const UserQuest_logsRoute = UserQuest_logsRouteImport.update({
  id: '/$user/quest_logs',
  path: '/$user/quest_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserMarket_logsRoute = UserMarket_logsRouteImport.update({
  id: '/$user/market_logs',
  path: '/$user/market_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserItemsRoute = UserItemsRouteImport.update({
  id: '/$user/items',
  path: '/$user/items',
  getParentRoute: () => rootRouteImport,
} as any)
const UserItem_logsRoute = UserItem_logsRouteImport.update({
  id: '/$user/item_logs',
  path: '/$user/item_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserForge_logsRoute = UserForge_logsRouteImport.update({
  id: '/$user/forge_logs',
  path: '/$user/forge_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCratesRoute = UserCratesRouteImport.update({
  id: '/$user/crates',
  path: '/$user/crates',
  getParentRoute: () => rootRouteImport,
} as any)
const UserConsumablesRoute = UserConsumablesRouteImport.update({
  id: '/$user/consumables',
  path: '/$user/consumables',
  getParentRoute: () => rootRouteImport,
} as any)
const UserClaim_logsRoute = UserClaim_logsRouteImport.update({
  id: '/$user/claim_logs',
  path: '/$user/claim_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBoss_logsRoute = UserBoss_logsRouteImport.update({
  id: '/$user/boss_logs',
  path: '/$user/boss_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBattle_logsRoute = UserBattle_logsRouteImport.update({
  id: '/$user/battle_logs',
  path: '/$user/battle_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockStatsRoute = ApiMockStatsRouteImport.update({
  id: '/api/mock/stats',
  path: '/api/mock/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockRichlistRoute = ApiMockRichlistRouteImport.update({
  id: '/api/mock/richlist',
  path: '/api/mock/richlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockQuest_boardRoute = ApiMockQuest_boardRouteImport.update({
  id: '/api/mock/quest_board',
  path: '/api/mock/quest_board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockMarketplace_logsRoute = ApiMockMarketplace_logsRouteImport.update({
  id: '/api/mock/marketplace_logs',
  path: '/api/mock/marketplace_logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockLeaderboardRoute = ApiMockLeaderboardRouteImport.update({
  id: '/api/mock/leaderboard',
  path: '/api/mock/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockItems_archiveRoute = ApiMockItems_archiveRouteImport.update({
  id: '/api/mock/items_archive',
  path: '/api/mock/items_archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockBattleRoute = ApiMockBattleRouteImport.update({
  id: '/api/mock/battle',
  path: '/api/mock/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockSalvage_logsUserRoute = ApiMockSalvage_logsUserRouteImport.update({
  id: '/api/mock/salvage_logs/$user',
  path: '/api/mock/salvage_logs/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockQuestsUserRoute = ApiMockQuestsUserRouteImport.update({
  id: '/api/mock/quests/$user',
  path: '/api/mock/quests/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockPlayerUserRoute = ApiMockPlayerUserRouteImport.update({
  id: '/api/mock/player/$user',
  path: '/api/mock/player/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockNft_logsUserRoute = ApiMockNft_logsUserRouteImport.update({
  id: '/api/mock/nft_logs/$user',
  path: '/api/mock/nft_logs/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockMarketplace_logsUserRoute =
  ApiMockMarketplace_logsUserRouteImport.update({
    id: '/$user',
    path: '/$user',
    getParentRoute: () => ApiMockMarketplace_logsRoute,
  } as any)
const ApiMockItemsUserRoute = ApiMockItemsUserRouteImport.update({
  id: '/api/mock/items/$user',
  path: '/api/mock/items/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockForge_logsUserRoute = ApiMockForge_logsUserRouteImport.update({
  id: '/api/mock/forge_logs/$user',
  path: '/api/mock/forge_logs/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockClaim_logsUserRoute = ApiMockClaim_logsUserRouteImport.update({
  id: '/api/mock/claim_logs/$user',
  path: '/api/mock/claim_logs/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockMarketplaceListingsRelicsRoute =
  ApiMockMarketplaceListingsRelicsRouteImport.update({
    id: '/api/mock/marketplace/listings/relics',
    path: '/api/mock/marketplace/listings/relics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMockMarketplaceListingsItemsRoute =
  ApiMockMarketplaceListingsItemsRouteImport.update({
    id: '/api/mock/marketplace/listings/items',
    path: '/api/mock/marketplace/listings/items',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMockMarketplaceListingsConsumablesRoute =
  ApiMockMarketplaceListingsConsumablesRouteImport.update({
    id: '/api/mock/marketplace/listings/consumables',
    path: '/api/mock/marketplace/listings/consumables',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/market_logs': typeof Market_logsRoute
  '/planets': typeof PlanetsRoute
  '/play': typeof PlayRoute
  '/richlist': typeof RichlistRoute
  '/shop': typeof ShopRoute
  '/stats': typeof StatsRoute
  '/$user/battle_logs': typeof UserBattle_logsRoute
  '/$user/boss_logs': typeof UserBoss_logsRoute
  '/$user/claim_logs': typeof UserClaim_logsRoute
  '/$user/consumables': typeof UserConsumablesRoute
  '/$user/crates': typeof UserCratesRoute
  '/$user/forge_logs': typeof UserForge_logsRoute
  '/$user/item_logs': typeof UserItem_logsRoute
  '/$user/items': typeof UserItemsRoute
  '/$user/market_logs': typeof UserMarket_logsRoute
  '/$user/quest_logs': typeof UserQuest_logsRoute
  '/$user/relics': typeof UserRelicsRoute
  '/$user/salvage_logs': typeof UserSalvage_logsRoute
  '/market/consumables': typeof MarketConsumablesRoute
  '/market/crates': typeof MarketCratesRoute
  '/market/relics': typeof MarketRelicsRoute
  '/quests/$mission': typeof QuestsMissionRoute
  '/market/': typeof MarketIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/api/mock/battle': typeof ApiMockBattleRoute
  '/api/mock/items_archive': typeof ApiMockItems_archiveRoute
  '/api/mock/leaderboard': typeof ApiMockLeaderboardRoute
  '/api/mock/marketplace_logs': typeof ApiMockMarketplace_logsRouteWithChildren
  '/api/mock/quest_board': typeof ApiMockQuest_boardRoute
  '/api/mock/richlist': typeof ApiMockRichlistRoute
  '/api/mock/stats': typeof ApiMockStatsRoute
  '/api/mock/claim_logs/$user': typeof ApiMockClaim_logsUserRoute
  '/api/mock/forge_logs/$user': typeof ApiMockForge_logsUserRoute
  '/api/mock/items/$user': typeof ApiMockItemsUserRoute
  '/api/mock/marketplace_logs/$user': typeof ApiMockMarketplace_logsUserRoute
  '/api/mock/nft_logs/$user': typeof ApiMockNft_logsUserRoute
  '/api/mock/player/$user': typeof ApiMockPlayerUserRoute
  '/api/mock/quests/$user': typeof ApiMockQuestsUserRoute
  '/api/mock/salvage_logs/$user': typeof ApiMockSalvage_logsUserRoute
  '/api/mock/marketplace/listings/consumables': typeof ApiMockMarketplaceListingsConsumablesRoute
  '/api/mock/marketplace/listings/items': typeof ApiMockMarketplaceListingsItemsRoute
  '/api/mock/marketplace/listings/relics': typeof ApiMockMarketplaceListingsRelicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/market_logs': typeof Market_logsRoute
  '/planets': typeof PlanetsRoute
  '/play': typeof PlayRoute
  '/richlist': typeof RichlistRoute
  '/shop': typeof ShopRoute
  '/stats': typeof StatsRoute
  '/$user/battle_logs': typeof UserBattle_logsRoute
  '/$user/boss_logs': typeof UserBoss_logsRoute
  '/$user/claim_logs': typeof UserClaim_logsRoute
  '/$user/consumables': typeof UserConsumablesRoute
  '/$user/crates': typeof UserCratesRoute
  '/$user/forge_logs': typeof UserForge_logsRoute
  '/$user/item_logs': typeof UserItem_logsRoute
  '/$user/items': typeof UserItemsRoute
  '/$user/market_logs': typeof UserMarket_logsRoute
  '/$user/quest_logs': typeof UserQuest_logsRoute
  '/$user/relics': typeof UserRelicsRoute
  '/$user/salvage_logs': typeof UserSalvage_logsRoute
  '/market/consumables': typeof MarketConsumablesRoute
  '/market/crates': typeof MarketCratesRoute
  '/market/relics': typeof MarketRelicsRoute
  '/quests/$mission': typeof QuestsMissionRoute
  '/market': typeof MarketIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/api/mock/battle': typeof ApiMockBattleRoute
  '/api/mock/items_archive': typeof ApiMockItems_archiveRoute
  '/api/mock/leaderboard': typeof ApiMockLeaderboardRoute
  '/api/mock/marketplace_logs': typeof ApiMockMarketplace_logsRouteWithChildren
  '/api/mock/quest_board': typeof ApiMockQuest_boardRoute
  '/api/mock/richlist': typeof ApiMockRichlistRoute
  '/api/mock/stats': typeof ApiMockStatsRoute
  '/api/mock/claim_logs/$user': typeof ApiMockClaim_logsUserRoute
  '/api/mock/forge_logs/$user': typeof ApiMockForge_logsUserRoute
  '/api/mock/items/$user': typeof ApiMockItemsUserRoute
  '/api/mock/marketplace_logs/$user': typeof ApiMockMarketplace_logsUserRoute
  '/api/mock/nft_logs/$user': typeof ApiMockNft_logsUserRoute
  '/api/mock/player/$user': typeof ApiMockPlayerUserRoute
  '/api/mock/quests/$user': typeof ApiMockQuestsUserRoute
  '/api/mock/salvage_logs/$user': typeof ApiMockSalvage_logsUserRoute
  '/api/mock/marketplace/listings/consumables': typeof ApiMockMarketplaceListingsConsumablesRoute
  '/api/mock/marketplace/listings/items': typeof ApiMockMarketplaceListingsItemsRoute
  '/api/mock/marketplace/listings/relics': typeof ApiMockMarketplaceListingsRelicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/items': typeof ItemsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/market_logs': typeof Market_logsRoute
  '/planets': typeof PlanetsRoute
  '/play': typeof PlayRoute
  '/richlist': typeof RichlistRoute
  '/shop': typeof ShopRoute
  '/stats': typeof StatsRoute
  '/$user/battle_logs': typeof UserBattle_logsRoute
  '/$user/boss_logs': typeof UserBoss_logsRoute
  '/$user/claim_logs': typeof UserClaim_logsRoute
  '/$user/consumables': typeof UserConsumablesRoute
  '/$user/crates': typeof UserCratesRoute
  '/$user/forge_logs': typeof UserForge_logsRoute
  '/$user/item_logs': typeof UserItem_logsRoute
  '/$user/items': typeof UserItemsRoute
  '/$user/market_logs': typeof UserMarket_logsRoute
  '/$user/quest_logs': typeof UserQuest_logsRoute
  '/$user/relics': typeof UserRelicsRoute
  '/$user/salvage_logs': typeof UserSalvage_logsRoute
  '/market/consumables': typeof MarketConsumablesRoute
  '/market/crates': typeof MarketCratesRoute
  '/market/relics': typeof MarketRelicsRoute
  '/quests/$mission': typeof QuestsMissionRoute
  '/market/': typeof MarketIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/api/mock/battle': typeof ApiMockBattleRoute
  '/api/mock/items_archive': typeof ApiMockItems_archiveRoute
  '/api/mock/leaderboard': typeof ApiMockLeaderboardRoute
  '/api/mock/marketplace_logs': typeof ApiMockMarketplace_logsRouteWithChildren
  '/api/mock/quest_board': typeof ApiMockQuest_boardRoute
  '/api/mock/richlist': typeof ApiMockRichlistRoute
  '/api/mock/stats': typeof ApiMockStatsRoute
  '/api/mock/claim_logs/$user': typeof ApiMockClaim_logsUserRoute
  '/api/mock/forge_logs/$user': typeof ApiMockForge_logsUserRoute
  '/api/mock/items/$user': typeof ApiMockItemsUserRoute
  '/api/mock/marketplace_logs/$user': typeof ApiMockMarketplace_logsUserRoute
  '/api/mock/nft_logs/$user': typeof ApiMockNft_logsUserRoute
  '/api/mock/player/$user': typeof ApiMockPlayerUserRoute
  '/api/mock/quests/$user': typeof ApiMockQuestsUserRoute
  '/api/mock/salvage_logs/$user': typeof ApiMockSalvage_logsUserRoute
  '/api/mock/marketplace/listings/consumables': typeof ApiMockMarketplaceListingsConsumablesRoute
  '/api/mock/marketplace/listings/items': typeof ApiMockMarketplaceListingsItemsRoute
  '/api/mock/marketplace/listings/relics': typeof ApiMockMarketplaceListingsRelicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/items'
    | '/leaderboard'
    | '/login'
    | '/market'
    | '/market_logs'
    | '/planets'
    | '/play'
    | '/richlist'
    | '/shop'
    | '/stats'
    | '/$user/battle_logs'
    | '/$user/boss_logs'
    | '/$user/claim_logs'
    | '/$user/consumables'
    | '/$user/crates'
    | '/$user/forge_logs'
    | '/$user/item_logs'
    | '/$user/items'
    | '/$user/market_logs'
    | '/$user/quest_logs'
    | '/$user/relics'
    | '/$user/salvage_logs'
    | '/market/consumables'
    | '/market/crates'
    | '/market/relics'
    | '/quests/$mission'
    | '/market/'
    | '/quests/'
    | '/api/mock/battle'
    | '/api/mock/items_archive'
    | '/api/mock/leaderboard'
    | '/api/mock/marketplace_logs'
    | '/api/mock/quest_board'
    | '/api/mock/richlist'
    | '/api/mock/stats'
    | '/api/mock/claim_logs/$user'
    | '/api/mock/forge_logs/$user'
    | '/api/mock/items/$user'
    | '/api/mock/marketplace_logs/$user'
    | '/api/mock/nft_logs/$user'
    | '/api/mock/player/$user'
    | '/api/mock/quests/$user'
    | '/api/mock/salvage_logs/$user'
    | '/api/mock/marketplace/listings/consumables'
    | '/api/mock/marketplace/listings/items'
    | '/api/mock/marketplace/listings/relics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/items'
    | '/leaderboard'
    | '/login'
    | '/market_logs'
    | '/planets'
    | '/play'
    | '/richlist'
    | '/shop'
    | '/stats'
    | '/$user/battle_logs'
    | '/$user/boss_logs'
    | '/$user/claim_logs'
    | '/$user/consumables'
    | '/$user/crates'
    | '/$user/forge_logs'
    | '/$user/item_logs'
    | '/$user/items'
    | '/$user/market_logs'
    | '/$user/quest_logs'
    | '/$user/relics'
    | '/$user/salvage_logs'
    | '/market/consumables'
    | '/market/crates'
    | '/market/relics'
    | '/quests/$mission'
    | '/market'
    | '/quests'
    | '/api/mock/battle'
    | '/api/mock/items_archive'
    | '/api/mock/leaderboard'
    | '/api/mock/marketplace_logs'
    | '/api/mock/quest_board'
    | '/api/mock/richlist'
    | '/api/mock/stats'
    | '/api/mock/claim_logs/$user'
    | '/api/mock/forge_logs/$user'
    | '/api/mock/items/$user'
    | '/api/mock/marketplace_logs/$user'
    | '/api/mock/nft_logs/$user'
    | '/api/mock/player/$user'
    | '/api/mock/quests/$user'
    | '/api/mock/salvage_logs/$user'
    | '/api/mock/marketplace/listings/consumables'
    | '/api/mock/marketplace/listings/items'
    | '/api/mock/marketplace/listings/relics'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/leaderboard'
    | '/login'
    | '/market'
    | '/market_logs'
    | '/planets'
    | '/play'
    | '/richlist'
    | '/shop'
    | '/stats'
    | '/$user/battle_logs'
    | '/$user/boss_logs'
    | '/$user/claim_logs'
    | '/$user/consumables'
    | '/$user/crates'
    | '/$user/forge_logs'
    | '/$user/item_logs'
    | '/$user/items'
    | '/$user/market_logs'
    | '/$user/quest_logs'
    | '/$user/relics'
    | '/$user/salvage_logs'
    | '/market/consumables'
    | '/market/crates'
    | '/market/relics'
    | '/quests/$mission'
    | '/market/'
    | '/quests/'
    | '/api/mock/battle'
    | '/api/mock/items_archive'
    | '/api/mock/leaderboard'
    | '/api/mock/marketplace_logs'
    | '/api/mock/quest_board'
    | '/api/mock/richlist'
    | '/api/mock/stats'
    | '/api/mock/claim_logs/$user'
    | '/api/mock/forge_logs/$user'
    | '/api/mock/items/$user'
    | '/api/mock/marketplace_logs/$user'
    | '/api/mock/nft_logs/$user'
    | '/api/mock/player/$user'
    | '/api/mock/quests/$user'
    | '/api/mock/salvage_logs/$user'
    | '/api/mock/marketplace/listings/consumables'
    | '/api/mock/marketplace/listings/items'
    | '/api/mock/marketplace/listings/relics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  Market_logsRoute: typeof Market_logsRoute
  PlanetsRoute: typeof PlanetsRoute
  PlayRoute: typeof PlayRoute
  RichlistRoute: typeof RichlistRoute
  ShopRoute: typeof ShopRoute
  StatsRoute: typeof StatsRoute
  UserBattle_logsRoute: typeof UserBattle_logsRoute
  UserBoss_logsRoute: typeof UserBoss_logsRoute
  UserClaim_logsRoute: typeof UserClaim_logsRoute
  UserConsumablesRoute: typeof UserConsumablesRoute
  UserCratesRoute: typeof UserCratesRoute
  UserForge_logsRoute: typeof UserForge_logsRoute
  UserItem_logsRoute: typeof UserItem_logsRoute
  UserItemsRoute: typeof UserItemsRoute
  UserMarket_logsRoute: typeof UserMarket_logsRoute
  UserQuest_logsRoute: typeof UserQuest_logsRoute
  UserRelicsRoute: typeof UserRelicsRoute
  UserSalvage_logsRoute: typeof UserSalvage_logsRoute
  QuestsMissionRoute: typeof QuestsMissionRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  ApiMockBattleRoute: typeof ApiMockBattleRoute
  ApiMockItems_archiveRoute: typeof ApiMockItems_archiveRoute
  ApiMockLeaderboardRoute: typeof ApiMockLeaderboardRoute
  ApiMockMarketplace_logsRoute: typeof ApiMockMarketplace_logsRouteWithChildren
  ApiMockQuest_boardRoute: typeof ApiMockQuest_boardRoute
  ApiMockRichlistRoute: typeof ApiMockRichlistRoute
  ApiMockStatsRoute: typeof ApiMockStatsRoute
  ApiMockClaim_logsUserRoute: typeof ApiMockClaim_logsUserRoute
  ApiMockForge_logsUserRoute: typeof ApiMockForge_logsUserRoute
  ApiMockItemsUserRoute: typeof ApiMockItemsUserRoute
  ApiMockNft_logsUserRoute: typeof ApiMockNft_logsUserRoute
  ApiMockPlayerUserRoute: typeof ApiMockPlayerUserRoute
  ApiMockQuestsUserRoute: typeof ApiMockQuestsUserRoute
  ApiMockSalvage_logsUserRoute: typeof ApiMockSalvage_logsUserRoute
  ApiMockMarketplaceListingsConsumablesRoute: typeof ApiMockMarketplaceListingsConsumablesRoute
  ApiMockMarketplaceListingsItemsRoute: typeof ApiMockMarketplaceListingsItemsRoute
  ApiMockMarketplaceListingsRelicsRoute: typeof ApiMockMarketplaceListingsRelicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richlist': {
      id: '/richlist'
      path: '/richlist'
      fullPath: '/richlist'
      preLoaderRoute: typeof RichlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets': {
      id: '/planets'
      path: '/planets'
      fullPath: '/planets'
      preLoaderRoute: typeof PlanetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market_logs': {
      id: '/market_logs'
      path: '/market_logs'
      fullPath: '/market_logs'
      preLoaderRoute: typeof Market_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/quests/$mission': {
      id: '/quests/$mission'
      path: '/quests/$mission'
      fullPath: '/quests/$mission'
      preLoaderRoute: typeof QuestsMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/relics': {
      id: '/market/relics'
      path: '/relics'
      fullPath: '/market/relics'
      preLoaderRoute: typeof MarketRelicsRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/crates': {
      id: '/market/crates'
      path: '/crates'
      fullPath: '/market/crates'
      preLoaderRoute: typeof MarketCratesRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/consumables': {
      id: '/market/consumables'
      path: '/consumables'
      fullPath: '/market/consumables'
      preLoaderRoute: typeof MarketConsumablesRouteImport
      parentRoute: typeof MarketRoute
    }
    '/$user/salvage_logs': {
      id: '/$user/salvage_logs'
      path: '/$user/salvage_logs'
      fullPath: '/$user/salvage_logs'
      preLoaderRoute: typeof UserSalvage_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/relics': {
      id: '/$user/relics'
      path: '/$user/relics'
      fullPath: '/$user/relics'
      preLoaderRoute: typeof UserRelicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/quest_logs': {
      id: '/$user/quest_logs'
      path: '/$user/quest_logs'
      fullPath: '/$user/quest_logs'
      preLoaderRoute: typeof UserQuest_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/market_logs': {
      id: '/$user/market_logs'
      path: '/$user/market_logs'
      fullPath: '/$user/market_logs'
      preLoaderRoute: typeof UserMarket_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/items': {
      id: '/$user/items'
      path: '/$user/items'
      fullPath: '/$user/items'
      preLoaderRoute: typeof UserItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/item_logs': {
      id: '/$user/item_logs'
      path: '/$user/item_logs'
      fullPath: '/$user/item_logs'
      preLoaderRoute: typeof UserItem_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/forge_logs': {
      id: '/$user/forge_logs'
      path: '/$user/forge_logs'
      fullPath: '/$user/forge_logs'
      preLoaderRoute: typeof UserForge_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/crates': {
      id: '/$user/crates'
      path: '/$user/crates'
      fullPath: '/$user/crates'
      preLoaderRoute: typeof UserCratesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/consumables': {
      id: '/$user/consumables'
      path: '/$user/consumables'
      fullPath: '/$user/consumables'
      preLoaderRoute: typeof UserConsumablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/claim_logs': {
      id: '/$user/claim_logs'
      path: '/$user/claim_logs'
      fullPath: '/$user/claim_logs'
      preLoaderRoute: typeof UserClaim_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/boss_logs': {
      id: '/$user/boss_logs'
      path: '/$user/boss_logs'
      fullPath: '/$user/boss_logs'
      preLoaderRoute: typeof UserBoss_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/battle_logs': {
      id: '/$user/battle_logs'
      path: '/$user/battle_logs'
      fullPath: '/$user/battle_logs'
      preLoaderRoute: typeof UserBattle_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/stats': {
      id: '/api/mock/stats'
      path: '/api/mock/stats'
      fullPath: '/api/mock/stats'
      preLoaderRoute: typeof ApiMockStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/richlist': {
      id: '/api/mock/richlist'
      path: '/api/mock/richlist'
      fullPath: '/api/mock/richlist'
      preLoaderRoute: typeof ApiMockRichlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/quest_board': {
      id: '/api/mock/quest_board'
      path: '/api/mock/quest_board'
      fullPath: '/api/mock/quest_board'
      preLoaderRoute: typeof ApiMockQuest_boardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/marketplace_logs': {
      id: '/api/mock/marketplace_logs'
      path: '/api/mock/marketplace_logs'
      fullPath: '/api/mock/marketplace_logs'
      preLoaderRoute: typeof ApiMockMarketplace_logsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/leaderboard': {
      id: '/api/mock/leaderboard'
      path: '/api/mock/leaderboard'
      fullPath: '/api/mock/leaderboard'
      preLoaderRoute: typeof ApiMockLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/items_archive': {
      id: '/api/mock/items_archive'
      path: '/api/mock/items_archive'
      fullPath: '/api/mock/items_archive'
      preLoaderRoute: typeof ApiMockItems_archiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/battle': {
      id: '/api/mock/battle'
      path: '/api/mock/battle'
      fullPath: '/api/mock/battle'
      preLoaderRoute: typeof ApiMockBattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/salvage_logs/$user': {
      id: '/api/mock/salvage_logs/$user'
      path: '/api/mock/salvage_logs/$user'
      fullPath: '/api/mock/salvage_logs/$user'
      preLoaderRoute: typeof ApiMockSalvage_logsUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/quests/$user': {
      id: '/api/mock/quests/$user'
      path: '/api/mock/quests/$user'
      fullPath: '/api/mock/quests/$user'
      preLoaderRoute: typeof ApiMockQuestsUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/player/$user': {
      id: '/api/mock/player/$user'
      path: '/api/mock/player/$user'
      fullPath: '/api/mock/player/$user'
      preLoaderRoute: typeof ApiMockPlayerUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/nft_logs/$user': {
      id: '/api/mock/nft_logs/$user'
      path: '/api/mock/nft_logs/$user'
      fullPath: '/api/mock/nft_logs/$user'
      preLoaderRoute: typeof ApiMockNft_logsUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/marketplace_logs/$user': {
      id: '/api/mock/marketplace_logs/$user'
      path: '/$user'
      fullPath: '/api/mock/marketplace_logs/$user'
      preLoaderRoute: typeof ApiMockMarketplace_logsUserRouteImport
      parentRoute: typeof ApiMockMarketplace_logsRoute
    }
    '/api/mock/items/$user': {
      id: '/api/mock/items/$user'
      path: '/api/mock/items/$user'
      fullPath: '/api/mock/items/$user'
      preLoaderRoute: typeof ApiMockItemsUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/forge_logs/$user': {
      id: '/api/mock/forge_logs/$user'
      path: '/api/mock/forge_logs/$user'
      fullPath: '/api/mock/forge_logs/$user'
      preLoaderRoute: typeof ApiMockForge_logsUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/claim_logs/$user': {
      id: '/api/mock/claim_logs/$user'
      path: '/api/mock/claim_logs/$user'
      fullPath: '/api/mock/claim_logs/$user'
      preLoaderRoute: typeof ApiMockClaim_logsUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/marketplace/listings/relics': {
      id: '/api/mock/marketplace/listings/relics'
      path: '/api/mock/marketplace/listings/relics'
      fullPath: '/api/mock/marketplace/listings/relics'
      preLoaderRoute: typeof ApiMockMarketplaceListingsRelicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/marketplace/listings/items': {
      id: '/api/mock/marketplace/listings/items'
      path: '/api/mock/marketplace/listings/items'
      fullPath: '/api/mock/marketplace/listings/items'
      preLoaderRoute: typeof ApiMockMarketplaceListingsItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/marketplace/listings/consumables': {
      id: '/api/mock/marketplace/listings/consumables'
      path: '/api/mock/marketplace/listings/consumables'
      fullPath: '/api/mock/marketplace/listings/consumables'
      preLoaderRoute: typeof ApiMockMarketplaceListingsConsumablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketRouteChildren {
  MarketConsumablesRoute: typeof MarketConsumablesRoute
  MarketCratesRoute: typeof MarketCratesRoute
  MarketRelicsRoute: typeof MarketRelicsRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketConsumablesRoute: MarketConsumablesRoute,
  MarketCratesRoute: MarketCratesRoute,
  MarketRelicsRoute: MarketRelicsRoute,
  MarketIndexRoute: MarketIndexRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface ApiMockMarketplace_logsRouteChildren {
  ApiMockMarketplace_logsUserRoute: typeof ApiMockMarketplace_logsUserRoute
}

const ApiMockMarketplace_logsRouteChildren: ApiMockMarketplace_logsRouteChildren =
  {
    ApiMockMarketplace_logsUserRoute: ApiMockMarketplace_logsUserRoute,
  }

const ApiMockMarketplace_logsRouteWithChildren =
  ApiMockMarketplace_logsRoute._addFileChildren(
    ApiMockMarketplace_logsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  Market_logsRoute: Market_logsRoute,
  PlanetsRoute: PlanetsRoute,
  PlayRoute: PlayRoute,
  RichlistRoute: RichlistRoute,
  ShopRoute: ShopRoute,
  StatsRoute: StatsRoute,
  UserBattle_logsRoute: UserBattle_logsRoute,
  UserBoss_logsRoute: UserBoss_logsRoute,
  UserClaim_logsRoute: UserClaim_logsRoute,
  UserConsumablesRoute: UserConsumablesRoute,
  UserCratesRoute: UserCratesRoute,
  UserForge_logsRoute: UserForge_logsRoute,
  UserItem_logsRoute: UserItem_logsRoute,
  UserItemsRoute: UserItemsRoute,
  UserMarket_logsRoute: UserMarket_logsRoute,
  UserQuest_logsRoute: UserQuest_logsRoute,
  UserRelicsRoute: UserRelicsRoute,
  UserSalvage_logsRoute: UserSalvage_logsRoute,
  QuestsMissionRoute: QuestsMissionRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  ApiMockBattleRoute: ApiMockBattleRoute,
  ApiMockItems_archiveRoute: ApiMockItems_archiveRoute,
  ApiMockLeaderboardRoute: ApiMockLeaderboardRoute,
  ApiMockMarketplace_logsRoute: ApiMockMarketplace_logsRouteWithChildren,
  ApiMockQuest_boardRoute: ApiMockQuest_boardRoute,
  ApiMockRichlistRoute: ApiMockRichlistRoute,
  ApiMockStatsRoute: ApiMockStatsRoute,
  ApiMockClaim_logsUserRoute: ApiMockClaim_logsUserRoute,
  ApiMockForge_logsUserRoute: ApiMockForge_logsUserRoute,
  ApiMockItemsUserRoute: ApiMockItemsUserRoute,
  ApiMockNft_logsUserRoute: ApiMockNft_logsUserRoute,
  ApiMockPlayerUserRoute: ApiMockPlayerUserRoute,
  ApiMockQuestsUserRoute: ApiMockQuestsUserRoute,
  ApiMockSalvage_logsUserRoute: ApiMockSalvage_logsUserRoute,
  ApiMockMarketplaceListingsConsumablesRoute:
    ApiMockMarketplaceListingsConsumablesRoute,
  ApiMockMarketplaceListingsItemsRoute: ApiMockMarketplaceListingsItemsRoute,
  ApiMockMarketplaceListingsRelicsRoute: ApiMockMarketplaceListingsRelicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
